version: '2.2'

services:

  traefik:
    image: traefik:v1.7-alpine
    container_name: traefik
    command: --api --docker --docker.domain=docker.localhost --logLevel=INFO \
      --defaultEntryPoints='http,https' \
      --entryPoints='Name:http Address::80' \
      --entryPoints='Name:https Address::443 TLS' \
      --entryPoints="Name:https Address::443 TLS:/etc/ssl/cert.crt,/etc/ssl/cert.key" \
      --docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssl:/etc/ssl
    ports:
      - "80:80/tcp"
      - "8080:8080/tcp"
      - "443:443/tcp"

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3324:3306/tcp"
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD -e \"SELECT 1\" $$MYSQL_DATABASE &> /dev/null" ]
      interval: 30s
      timeout: 30s
      retries: 3

  www-test:
    image: test-www:latest
    container_name: www-test
    hostname: www-test
    labels:
      - "traefik.enable=true"
      - "traefik.backend=www-test"
      - "traefik.frontend.rule=Host:laravel.dev.me"
    environment:
      - ENV_TOKEN_ID=${ENV_TOKEN_ID-}
      - ENV_DOMAIN_ID=${ENV_DOMAIN_ID-.dev.me}
      - XDEBUG_ENABLE=${XDEBUG_ENABLE-no}
      - BLACKFIRE_ENABLE=${BLACKFIRE_ENABLE-no}
    volumes:
      - ../:/www
    depends_on:
      - db
      - traefik

volumes:
  db_data: {}
